import { NextRequest } from 'next/server';
import { protectedRoute } from '@/lib/route-helper';
import { sendEmail } from '@/lib/email';
import prisma from '@/lib/db';

export const POST = protectedRoute(async (request: NextRequest) => {
    // We'll use the current user's email as the recipient
    const userId = request.headers.get('x-user-id');
    const user = await prisma.user.findUnique({
        where: { id: userId || '' },
        select: { email: true, username: true }
    });

    if (!user || !user.email) {
        return Response.json({
            success: false,
            message: 'Your user account does not have an email address configured. Cannot send test.'
        }, { status: 400 });
    }

    const success = await sendEmail({
        to: user.email,
        subject: '🧪 SMTP Test - INSOPHINIA POS',
        html: `
            <div style="font-family: sans-serif; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
                <h2 style="color: #4f46e5;">SMTP Connection Successful!</h2>
                <p>Hello <strong>${user.username}</strong>,</p>
                <p>This is a test email from your INSOPHINIA POS system to verify that your SMTP settings are configured correctly.</p>
                <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;">
                <p style="font-size: 12px; color: #64748b;">
                    Sent at: ${new Date().toLocaleString()}<br>
                    Generated by: INSOPHINIA POS System
                </p>
            </div>
        `
    });

    if (success) {
        return Response.json({ success: true, message: `Test email sent to ${user.email}. Check your inbox!` });
    } else {
        return Response.json({
            success: false,
            message: 'Failed to send test email. Please check your SMTP configuration in Settings and ensure EMAIL_ENABLED="true" in .env'
        }, { status: 500 });
    }
}, { requiredRole: 'admin' });
